name: test and lint
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: install package
        run: make install
      - name: test
        run: npx jest
      - name: lint
        run: make lint