name: main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: npm install
      - run: make lint
      - name: test
        run: npx jest
      
      - uses: paambaati/codeclimate-action@v3.2.0
      - env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      - with:
        coverageCommand: npx jest --coverage
        debug: true
     