name: main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: npm install
      - run: make lint
      - name: test
        run: npx jest
      - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v3.2.0
      env:
        CC_TEST_REPORTER_ID:  ${{ secrets.MAIN_SECRET }}
      with:
        coverageCommand: npm run coverage
        debug: true
     