name: test and lint

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: cypress-io/github-action@v2
      - run: npm install
      - run: make lint
      - name: test
        run: npx jest
     